baseURL = 'https://piotrooo.codes'
languageCode = 'en-us'
title = "piotrooo's codes"
theme = 'archie'
copyright = '© Piotr Olaszewski'
disqusShortname = ""

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    ID = 'G-6HS4BEX4CF'

[params]
mode = 'toggle'
useCDN = false
subtitle = "Software Architect's diary"
customcss = ['/css/piotrooo.css']

[[params.social]]
name = 'GitHub'
icon = 'simple:github'
url = 'https://github.com/piotrooo'

[[params.social]]
name = 'Twitter'
icon = 'simple:bluesky'
url = 'https://bsky.app/profile/piotrooo.bsky.social'

[[params.social]]
name = 'Twitter'
icon = 'simple:x'
url = 'https://twitter.com/_piotrooo'

[[params.social]]
name = 'LinkedIn'
icon = 'simple:linkedin'
url = 'https://www.linkedin.com/in/piotrooo/'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'All posts'
url = '/posts'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3
