baseURL = 'https://piotrooo.codes'
languageCode = 'en-us'
title = "piotrooo's codes"
theme = 'archie'
copyright = '© Piotr Olaszewski'

paginate = 5

[services]
  [services.googleAnalytics]
    ID = 'G-6HS4BEX4CF'

[params]
mode = 'toggle'
useCDN = false
subtitle = "Backend Tech Lead's diary"

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/piotrooo'

[[params.social]]
name = 'Twitter'
icon = 'twitter'
url = 'https://twitter.com/_piotrooo'

[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/piotrooo/'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'All posts'
url = '/posts'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3
